; PlatformIO Configuration File for AquaSentinel Buoy Node (ESP32)
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    sandeepmistry/LoRa @ 0.8.0
    milesburton/DallasTemperature @ 3.9.1
    paulstoffregen/OneWire @ 2.3.7
    bblanchon/ArduinoJson @ 7.0.4
