"""Initial schema setup with spatial structures and operational tables

Revision ID: 92389ac03927
Revises: 
Create Date: 2026-07-10 10:27:16.251631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92389ac03927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gateway_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_temp', sa.Float(), nullable=True),
    sa.Column('ram_usage_pct', sa.Float(), nullable=True),
    sa.Column('disk_usage_pct', sa.Float(), nullable=True),
    sa.Column('network_type', sa.String(length=20), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('calibration_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=False),
    sa.Column('ph_offset', sa.Float(), nullable=False),
    sa.Column('ph_slope', sa.Float(), nullable=False),
    sa.Column('turbidity_zero_offset', sa.Float(), nullable=False),
    sa.Column('water_level_offset_cm', sa.Float(), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operator_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_nodes.sensor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_commands',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=False),
    sa.Column('command_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_nodes.sensor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_acknowledgements',
    sa.Column('command_id', sa.String(length=40), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['device_commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('command_id')
    )
    op.create_table('telemetry_quality_flags',
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('is_ph_valid', sa.Boolean(), nullable=False),
    sa.Column('is_turbidity_valid', sa.Boolean(), nullable=False),
    sa.Column('is_water_level_valid', sa.Boolean(), nullable=False),
    sa.Column('is_battery_valid', sa.Boolean(), nullable=False),
    sa.Column('is_tilt_valid', sa.Boolean(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['telemetry_readings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_table('alert_acknowledgements',
    sa.Column('alert_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('alert_assignments',
    sa.Column('alert_id', sa.String(length=40), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=40), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by_user_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_events')
    op.drop_table('alert_assignments')
    op.drop_table('alert_acknowledgements')
    op.drop_table('telemetry_quality_flags')
    op.drop_table('command_acknowledgements')
    op.drop_table('device_commands')
    op.drop_table('calibration_history')
    op.drop_table('user_roles')
    op.drop_table('gateway_health_logs')
    op.drop_table('roles')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
